version: '3'
services:
  python3:
    restart: always
    build: .
    image: python-img
    container_name: python3
    working_dir: /work
    tty: true
    volumes:
      - type: bind
        source: ../
        target: /work
    ports:
      - "8000:8888"
    command:
      jupyter-lab --ip 0.0.0.0 --allow-root -b localhost
